female(lena).
female(marina).
female(natasha).
female(katya).
female(tamera).
female(jennie).
female(lucy).
female(liza).
female(tanya).
male(john).
male(tomy).
male(levi).
male(arthur).
male(zach).
male(madison).
male(addy).
male(andy).
male(jame).
parent(lena,marina).
parent(john,marina).
parent(lena,tomy).
parent(john,tomy).
parent(lena,zach).
parent(john,zach).
parent(madison,jennie).
parent(tamera,jennie).
parent(madison,addy).
parent(tamera,addy).
parent(tomy,andy).
parent(natasha,andy).
parent(tomy,katya).
parent(natasha,katya).
parent(tomy,liza).
parent(natasha,liza).
parent(zach,lucy).
parent(jennie,lucy).
parent(levi,arthur).
parent(katya,arthur).
parent(lucy,tanya).
parent(jame,tanya).
spouse(john,lena).
spouse(madison,tamera).
spouse(tomy,natasha).
spouse(zach,jennie).
spouse(levi,katya).
spouse(lucy,jame).

grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandfather(X,Y):-parent(X,Z),parent(Z,Y),male(X).
grandmother(X,Y):-parent(X,Z),parent(Z,Y),female(X).
son(X,Y):-parent(Y,X),male(X).
daughter(X,Y):-parent(Y,X),female(X).
grandson(X,Y):-parent(Z,X),parent(Y,Z),male(X).
granddaughter(X,Y):-parent(Z,X),parent(Y,Z),female(X).
sibling(X,Y):- parent(Z,X), parent(Z,Y), X\==Y.
mother(X,Y):-parent(X,Y),female(X).
father(X,Y):-parent(X,Y),male(X).
haschild(X):-parent(X,_).
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X),X\==Y.
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X),X\==Y.
uncle(X,Y):-parent(Z,Y),parent(T,X),parent(T,Z),male(X),X\==Z.
aunt(X,Y):-parent(Z,Y),parent(T,X),parent(T,Z),female(X),X\==Z.